
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres_db" ]
      interval: 5s
      retries: 5
      start_period: 10s

networks:
  backend_network:
    driver: bridge